"""
modules/market_data/upstox/upstox_auth_client.py

The single place that owns Upstox authentication. Every Upstox data module
(instrument list, OHLCV, fundamentals) imports a ready-to-use, pre-authenticated
HTTP session from here -- exactly the way the Dhan side does
`from dhan_client import dhan`. The dependency points one way: this module knows
nothing about candles, fundamentals, or watchlists; the fetchers depend on it.

Design notes / ADR:
  - AUTH MECHANISM: Upstox's Analytics Token -- a long-lived (1-year), read-only
    Bearer JWT generated once from the Developer Apps -> Analytics tab. No OAuth
    redirect, no daily refresh, free. Confirmed 2026-08-23 to cover everything
    Fortuna needs (Instrument Search, Historical candle, Fundamentals, Option
    Chain, Market Info, News) with NO static IP required. Only trading + account-
    state APIs (orders/portfolio/funds/P&L) are out of scope for this token -- and
    Fortuna never does those via Upstox (that is Dhan's job).
  - WHY A raw requests.Session, NOT the official upstox-python-sdk: the SDK is a
    heavyweight OpenAPI-generated client built around the OAuth/trading surface
    (Configuration -> ApiClient -> per-area ApiV3 classes), ~95% of which is order
    placement this read-only token cannot use. A plain Bearer header on a
    requests.Session is ~5 lines, adds no heavy dependency, keeps the hand-rolled
    retry/backoff/throttle control the universe backfill needs, and lets the
    fetchers keep the same FetchResult(ok=...) shape used on the Dhan side. Upstox's
    own docs confirm the Analytics Token works as a plain Bearer token, so we lose
    no capability by skipping the SDK.
  - TRADING PATH IS DELIBERATELY DEFERRED (Rule #16): the Analytics Token is
    read-only by API contract and can NEVER place orders. If Ash later decides to
    trade via Upstox (a decision to be made only after Fortuna is complete; pricing
    plans may change), that needs Upstox's standard daily-OAuth flow -- a fully
    separate mechanism, not an upgrade of this token. `get_trading_client()` is a
    stub that fails loudly rather than silently missing, so the seam is visible and
    additive later without reworking anything here.

Standards applied: single responsibility (owns auth only), fail-loud on missing
config (a config bug is not a runtime state to swallow), defensive programming,
bounded retry w/ exponential backoff on transient network/5xx, structured logging
(NEVER logs the token or any secret), stdlib + requests + python-dotenv only.
Deferred (not applicable to an auth/session provider): DB/migrations, caching,
the trading client (see Rule #16 above), app-side rate limiting (each fetcher
throttles itself against Upstox's 25/sec, 250/min, 1000/30min limits).
KNOWN GAP -- token-expiry is checked only opportunistically (a warn-level log when
within EXPIRY_WARN_DAYS of the 1-year expiry, decoded from the JWT's own `exp`
claim WITHOUT verifying the signature -- we're reading our own token for a date,
not trusting it as a security boundary). There is no auto-renewal: the Analytics
Token must be regenerated by hand in the Developer console, so the warning is the
mechanism, by design.
"""

from __future__ import annotations

import base64
import binascii
import json
import logging
import os
import time
from dataclasses import dataclass
from datetime import date, datetime, timezone
from typing import Optional

import requests
from dotenv import load_dotenv

logger = logging.getLogger(__name__)

# python-dotenv is a no-op if there is no .env file (e.g. on Render, where env
# vars come from the dashboard), so the same code path works locally and in prod.
load_dotenv()

# --- Config (kept out of function bodies so it's easy to tune) -------------

UPSTOX_BASE_URL = "https://api.upstox.com"
_ANALYTICS_TOKEN_ENV = "UPSTOX_ANALYTICS_TOKEN"

# Smoke test uses Market Status (v2): no parameters, lightweight, and a clean 200
# proves the token authenticates against the account. NOTE: the base URL is
# version-AGNOSTIC (no /v2 or /v3 baked in) because Upstox mixes versions —
# instrument/market APIs are v2, historical candles are v3. Each caller supplies
# the full versioned path (e.g. '/v2/market/status/NSE', '/v3/historical-candle/...').
_SMOKE_TEST_PATH = "/v2/market/status/NSE"

DEFAULT_TIMEOUT_SECONDS = 15          # per-call wall clock (requests-level)
MAX_RETRIES = 3
BACKOFF_BASE_SECONDS = 1.0            # 1s, 2s, 4s
_RETRIABLE_STATUS = {429, 500, 502, 503, 504}

EXPIRY_WARN_DAYS = 30                 # warn when the 1-year token is this close to expiry


class UpstoxAuthError(RuntimeError):
    """Raised for auth/config problems that are BUGS to fix (missing token, etc.),
    not runtime conditions to degrade around."""


@dataclass
class SmokeResult:
    """Normalised result of the auth smoke test. `ok` is the single flag to
    check. `detail` explains a failure without leaking the token."""
    ok: bool
    status_code: Optional[int] = None
    detail: Optional[str] = None


# --- Token loading + expiry awareness --------------------------------------

def _load_analytics_token() -> str:
    """Read the Analytics Token from the environment. Fail loudly if absent --
    a missing credential is a setup bug, surfaced immediately, never a silent
    empty string that 401s cryptically later."""
    token = os.environ.get(_ANALYTICS_TOKEN_ENV, "").strip()
    if not token:
        raise UpstoxAuthError(
            f"{_ANALYTICS_TOKEN_ENV} is not set. Generate an Analytics Token at "
            f"Upstox Developer Apps -> Analytics tab -> Generate Token, and put the "
            f"full value in your .env as {_ANALYTICS_TOKEN_ENV}=..."
        )
    return token


def _token_expiry_date(token: str) -> Optional[date]:
    """
    Best-effort read of the JWT `exp` claim to get the token's expiry date.
    We decode the payload WITHOUT verifying the signature on purpose: this is
    our own token and we only want a date for a courtesy warning, not a trust
    decision. Returns None if the token isn't a decodable JWT (in which case we
    simply skip the expiry warning rather than erroring).
    """
    try:
        parts = token.split(".")
        if len(parts) != 3:
            return None
        payload_b64 = parts[1]
        padding = "=" * (-len(payload_b64) % 4)          # base64url needs padding restored
        payload_raw = base64.urlsafe_b64decode(payload_b64 + padding)
        payload = json.loads(payload_raw)
        exp = payload.get("exp")
        if exp is None:
            return None
        return datetime.fromtimestamp(float(exp), tz=timezone.utc).date()
    except (ValueError, TypeError, binascii.Error, json.JSONDecodeError):
        # Not a readable JWT -> no warning, not an error. The token may still be
        # a perfectly valid opaque credential.
        return None


def _warn_if_expiring(token: str) -> None:
    expiry = _token_expiry_date(token)
    if expiry is None:
        return
    days_left = (expiry - date.today()).days
    if days_left < 0:
        logger.error(
            "Upstox Analytics Token EXPIRED on %s. Regenerate it in the Developer "
            "console (Analytics tab) and update %s in .env.",
            expiry.isoformat(), _ANALYTICS_TOKEN_ENV,
        )
    elif days_left <= EXPIRY_WARN_DAYS:
        logger.warning(
            "Upstox Analytics Token expires in %d day(s) on %s. Plan to regenerate "
            "it before then -- all Upstox data fetches stop working once it lapses.",
            days_left, expiry.isoformat(),
        )


# --- The authenticated session (module-level singleton) --------------------

_session: Optional[requests.Session] = None


def get_analytics_client() -> requests.Session:
    """
    Return a process-wide, ready-authenticated requests.Session for the Upstox
    Analytics Token. Fetch modules import and use this the way the Dhan side uses
    the `dhan` SDK object -- they never touch the token themselves.

    Built lazily and cached: the first call loads the token, checks expiry, and
    sets the Bearer + Accept headers once; later calls reuse the same session
    (connection pooling for free).
    """
    global _session
    if _session is not None:
        return _session

    token = _load_analytics_token()
    _warn_if_expiring(token)

    session = requests.Session()
    session.headers.update({
        "Accept": "application/json",
        "Authorization": f"Bearer {token}",
    })
    _session = session
    logger.info("Upstox analytics session initialised (base=%s).", UPSTOX_BASE_URL)
    return _session


def get_trading_client() -> requests.Session:
    """
    STUB -- NOT IMPLEMENTED (Rule #16 -- Broker-Agnostic Design).

    The Analytics Token is read-only by API contract and cannot place, modify, or
    cancel orders. Trading via Upstox would require Upstox's standard daily-OAuth
    access token (a separate app registration + daily-refresh automation, e.g. a
    TOTP headless login), which is a distinct mechanism from the Analytics Token,
    not an extension of it. This is deliberately deferred until Ash decides -- after
    Fortuna is complete -- whether to route any execution through Upstox. The seam
    exists so that decision is additive and never forces a rewrite of this module.
    """
    raise NotImplementedError(
        "Upstox trading client is intentionally not built (Rule #16). The Analytics "
        "Token is read-only. Placing orders via Upstox needs the standard daily-OAuth "
        "flow + refresh automation, to be added only if/when Ash decides to trade via "
        "Upstox. See the module docstring / Fortuna roadmap doc."
    )


# --- Shared authenticated GET with bounded retry ---------------------------

def request_get(
    path: str,
    params: Optional[dict] = None,
    *,
    timeout: float = DEFAULT_TIMEOUT_SECONDS,
) -> requests.Response:
    """
    Perform an authenticated GET against the Upstox API with bounded retry and
    exponential backoff on transient failures (network errors + 429/5xx). `path`
    must be the FULL versioned path (e.g. '/v2/market/status/NSE' or
    '/v3/historical-candle/...') since the base URL is version-agnostic. Returns
    the raw requests.Response so each fetcher can parse in its own domain shape —
    this is plumbing, not a parser.

    Retries only transient conditions. A 4xx (other than 429) is returned as-is on
    the first try: it's a caller/request problem (bad instrument key, bad params),
    not something a retry fixes. Raises the last exception only if every network
    attempt itself failed to complete.
    """
    session = get_analytics_client()
    url = f"{UPSTOX_BASE_URL}{path}"
    last_exc: Optional[Exception] = None

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            resp = session.get(url, params=params, timeout=timeout)
            if resp.status_code in _RETRIABLE_STATUS and attempt < MAX_RETRIES:
                wait = BACKOFF_BASE_SECONDS * (2 ** (attempt - 1))
                logger.warning(
                    "Upstox GET %s -> HTTP %d (attempt %d/%d). Retrying in %.1fs.",
                    path, resp.status_code, attempt, MAX_RETRIES, wait,
                )
                time.sleep(wait)
                continue
            return resp
        except requests.RequestException as exc:
            last_exc = exc
            wait = BACKOFF_BASE_SECONDS * (2 ** (attempt - 1))
            logger.warning(
                "Upstox GET %s failed (attempt %d/%d): %s. Retrying in %.1fs.",
                path, attempt, MAX_RETRIES, exc, wait,
            )
            if attempt < MAX_RETRIES:
                time.sleep(wait)

    assert last_exc is not None
    raise last_exc


# --- Smoke test ------------------------------------------------------------

def smoke_test() -> SmokeResult:
    """
    Prove the Analytics Token authenticates against the account by making one real,
    parameter-free read call (Market Status). Returns SmokeResult(ok=...) rather
    than raising for expected failure modes, so it's safe to call from a startup
    check or a CLI. A 200 with status="success" is the pass condition.
    """
    try:
        resp = request_get(_SMOKE_TEST_PATH)
    except UpstoxAuthError as exc:
        return SmokeResult(ok=False, detail=str(exc))
    except requests.RequestException as exc:
        return SmokeResult(ok=False, detail=f"network error: {exc}")

    if resp.status_code == 401:
        return SmokeResult(
            ok=False, status_code=401,
            detail="401 Unauthorized -- token is invalid/expired or not the Analytics Token.",
        )
    if resp.status_code != 200:
        # Body may carry an Upstox error message; include a short, non-secret slice.
        return SmokeResult(
            ok=False, status_code=resp.status_code,
            detail=f"unexpected HTTP {resp.status_code}: {resp.text[:200]}",
        )

    try:
        body = resp.json()
    except ValueError:
        return SmokeResult(ok=False, status_code=200, detail="200 but body was not JSON.")

    if body.get("status") != "success":
        return SmokeResult(
            ok=False, status_code=200,
            detail=f"200 but status!='success': {str(body)[:200]}",
        )

    logger.info("Upstox smoke test passed (HTTP 200, status=success).")
    return SmokeResult(ok=True, status_code=200, detail="authenticated")


if __name__ == "__main__":
    # Manual smoke test: `python -m modules.market_data.upstox.upstox_auth_client`
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    result = smoke_test()
    if result.ok:
        print("PASS -- Upstox Analytics Token authenticated successfully.")
    else:
        print(f"FAIL -- {result.detail}")
        raise SystemExit(1)
